# Generated by Django 4.2.1 on 2023-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user',
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='MyUser'),
        ),
    ]
